# Generated by Django 3.2.14 on 2022-10-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_changedpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=255, null=True, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.CharField(max_length=255, null=True, verbose_name='country code'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.BooleanField(default=True, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=255, null=True, verbose_name='phone'),
        ),
    ]
