# Generated by Django 3.2.14 on 2022-08-11 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=150)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('summit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summit.summit')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('oragnization', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[(1, 'Tashrif buyuruvchi'), (2, 'Ishtirokchi'), (3, 'Spiker'), (4, 'OAV')], max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('summit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='summit.summit')),
            ],
        ),
    ]
