# Generated by Django 3.2.14 on 2022-07-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220724_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagequestion',
            old_name='product',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='imagequestion',
            name='name',
        ),
        migrations.AlterField(
            model_name='imagequestion',
            name='default',
            field=models.BooleanField(default=True),
        ),
    ]
