# Generated by Django 3.2.14 on 2022-08-08 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Code',
        ),
    ]
