# Generated by Django 3.2.14 on 2022-08-13 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20220810_0035'),
        ('posts', '0011_auto_20220812_1733'),
    ]

    operations = [
    ]
