# Generated by Django 3.2.14 on 2022-08-22 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20220813_1926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-id'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='articlereview',
            options={'verbose_name': 'Комментарии к статье', 'verbose_name_plural': 'Комментарии к статьям'},
        ),
        migrations.AlterModelOptions(
            name='imagequestion',
            options={'verbose_name': 'Изображения вопроса', 'verbose_name_plural': 'Изображении вопросов'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-id'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='newsreview',
            options={'verbose_name': 'Комментарии к новостью', 'verbose_name_plural': 'Комментарии к новостям'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-id'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
