# Generated by Django 3.2.14 on 2022-08-23 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20220817_1732'),
        ('posts', '0014_auto_20220822_1809'),
    ]

    operations = [
    ]
