# Generated by Django 3.2.14 on 2022-08-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_merge_0014_auto_20220817_1732_0014_auto_20220822_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Article/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='imagequestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='QuestionImages/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='News/%y/%m/%d'),
        ),
    ]
