# Generated by Django 3.2.14 on 2022-09-20 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0019_rename_new_userlikednews_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlikednews',
            name='news',
        ),
        migrations.RemoveField(
            model_name='userlikednews',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userlikedquestions',
            name='question',
        ),
        migrations.RemoveField(
            model_name='userlikedquestions',
            name='user',
        ),
        migrations.AddField(
            model_name='article',
            name='user_liked',
            field=models.ManyToManyField(null=True, related_name='user_liked_a', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='news',
            name='user_liked',
            field=models.ManyToManyField(null=True, related_name='user_liked_n', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='user_liked',
            field=models.ManyToManyField(null=True, related_name='user_liked_q', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserLikedArticles',
        ),
        migrations.DeleteModel(
            name='UserLikedNews',
        ),
        migrations.DeleteModel(
            name='UserLikedQuestions',
        ),
    ]
