# Generated by Django 3.2.14 on 2022-09-20 20:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0020_auto_20220920_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='view_count',
        ),
        migrations.AddField(
            model_name='news',
            name='view_count',
            field=models.ManyToManyField(related_name='user_viewed_n', to=settings.AUTH_USER_MODEL),
        ),
    ]
