# Generated by Django 3.2.14 on 2022-09-27 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_auto_20220921_0925'),
        ('posts', '0022_auto_20220927_0125'),
    ]

    operations = [
    ]
