# Generated by Django 3.2.14 on 2022-10-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_auto_20221001_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
