# Generated by Django 3.2.14 on 2022-10-27 20:56

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_auto_20221001_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='subtitle',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='subtitle',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='subtitle',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='name_az',
            field=models.CharField(max_length=50, null=True, verbose_name='Name in azerbaijanian'),
        ),
        migrations.AddField(
            model_name='theme',
            name='name_kr',
            field=models.CharField(max_length=50, null=True, verbose_name='Name in kyrgyzian'),
        ),
        migrations.AddField(
            model_name='theme',
            name='name_kz',
            field=models.CharField(max_length=50, null=True, verbose_name='Name in kazakhian'),
        ),
        migrations.AddField(
            model_name='theme',
            name='name_tu',
            field=models.CharField(max_length=50, null=True, verbose_name='Name in turkish'),
        ),
        migrations.AddField(
            model_name='theme',
            name='name_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Name in uzbek'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name in english'),
        ),
    ]
