# Generated by Django 3.2.14 on 2022-11-01 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0029_theme_preview_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='saved_collections',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_saved_a', to=settings.AUTH_USER_MODEL),
        ),
    ]
