# Generated by Django 3.2.14 on 2022-11-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_alter_article_saved_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='useruploadimage',
            name='is_moderated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useruploadimage',
            name='image',
            field=models.ImageField(default='img/user/defaultUser.jpg', upload_to='UserUploadImage/%y/%m/%d'),
        ),
    ]
