name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "/root/tour_agency"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          /root/smartcities/venv/bin/pip install -r /root/smartcities/requirements/production.txt
          /root/smartcities/venv/bin/python /root/smartcities/manage.py migrate
          /root/smartcities/venv/bin/python /root/smartcities/manage.py compilemessages
          /root/smartcities/venv/bin/python /root/smartcities/manage.py collectstatic
          systemctl restart gunicorn.service
